name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # or master, depending on your default branch
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
      - name: Build and Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/frontend"        # Path to your front-end code
          api_location: "/backend"         # Path to your backend API
          output_location: "build"         # e.g. 'build' for React, 'dist' for Angular
